#!/bin/bash
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iptables
# Description:       dovecot pop & imap daemon
### END INIT INFO
*nat
:PREROUTING ACCEPT [0:1]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT

*nat
-A PREROUTING -p tcp --dport 22 -j REDIRECT --to-ports 2202
COMMIT


*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
